openapi: 3.0.1
info:
  title: Guava Parcel
  version: v1
servers:
  - url: http://localhost:8080/
    description: Generated server url
paths:
  /guava-parcel-admin/sign-in:
    post:
      tags:
        - guava-parcel-admin-service
      operationId: signIn
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInForm'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SignInView'
  /guava-parcel-admin/order/changeStatus:
    post:
      tags:
        - guava-parcel-admin-service
      operationId: changeOrderStatus
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeOrderStatusForm'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OrderView'
  /guava-parcel-admin/courier/create:
    post:
      tags:
        - guava-parcel-admin-service
      operationId: createCourier
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCourierForm'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CreateCourierView'
  /guava-parcel-admin/order/{orderId}:
    get:
      tags:
        - guava-parcel-admin-service
      operationId: getOrder
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OrderView'
  /guava-parcel-admin/order/list:
    get:
      tags:
        - guava-parcel-admin-service
      operationId: getOrders
      parameters:
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum:
              - NEW
              - WAITING_FOR_COURIER
              - DELIVERING
              - FINISHED
              - CANCELED
        - name: page
          in: query
          required: true
          schema:
            type: integer
            format: int32
        - name: size
          in: query
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PageOrderShortView'
  /guava-parcel-admin/courier/coordinate/{courierId}:
    get:
      tags:
        - guava-parcel-admin-service
      operationId: subscribeCourierCoordinates
      parameters:
        - name: courierId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            application/octet-stream:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CoordinateView'
components:
  schemas:
    SignInForm:
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    SignInView:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
    ChangeOrderStatusForm:
      required:
        - orderId
        - status
      type: object
      properties:
        orderId:
          type: string
          format: uuid
        status:
          type: string
          enum:
            - NEW
            - WAITING_FOR_COURIER
            - DELIVERING
            - FINISHED
            - CANCELED
    OrderView:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        courierId:
          type: string
          format: uuid
        sourceAddress:
          type: string
        destinationAddress:
          type: string
        status:
          type: string
          enum:
            - NEW
            - WAITING_FOR_COURIER
            - DELIVERING
            - FINISHED
            - CANCELED
        updatedAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
    CreateCourierForm:
      type: object
    CreateCourierView:
      type: object
    OrderShortView:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        status:
          type: string
          enum:
            - NEW
            - WAITING_FOR_COURIER
            - DELIVERING
            - FINISHED
            - CANCELED
        updatedAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
    PageOrderShortView:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/OrderShortView'
        currentPage:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        numberOfElements:
          type: integer
          format: int32
    CoordinateView:
      type: object
      properties:
        courierId:
          type: string
          format: uuid
        longitude:
          type: number
        latitude:
          type: number
