spring:
  main:
    banner-mode: off
  application:
    name: "guava-parcel-admin"
  cloud:
    consul:
      host: "localhost"
      port: 8500
      discovery:
        prefer-ip-address: true
        health-check-interval: 15s
        health-check-timeout: 60s
        health-check-critical-timeout: 3m
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.guava.parcel.admin.config.DeliveryServiceClientConfig: TRACE

clients:
  delivery-service:
    http-client:
      read-timeout: 3000
      write-timeout: 3000
      connect-timeout: 3000
      response-timeout: 3000
    retry:
      max-retry: 3
      retry-interval: 3000
    urls:
      base-url: http://guava-parcel-delivry
