version: '3.8'

services:
  guava-postgresql:
    image: 'postgres:12.1'
    environment:
      - POSTGRES_USER=guava
      - POSTGRES_PASSWORD=guava
    ports:
      - '5432:5432'
  consul:
    image: 'consul:latest'
    ports:
      - "8500:8500"
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9093:9093"
    environment:
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_BROKER_ID=1
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093,CONTROLLER://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9094,2@kafka2:9094
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=XBXRUWjxTDe3ZuGUJrFyiA
  kafka-ui:
    container_name: kafka-ui
    image: 'provectuslabs/kafka-ui:latest'
    ports:
      - "9004:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
  pgadmin:
    image: 'pgadmin:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: test@email
      PGADMIN_DEFAULT_PASSWORD: test
    ports:
      - "9000:80"
  guava-parcel-gateway:
    build: ../guava-parcel-gateway
    ports:
      - "8080:8080"
    environment:
      - CONSUL_SERVER_HOST=consul
      - CONSUL_SERVER_PORT=8500
    depends_on:
      - consul
  guava-parcel-auth:
    build: ../guava-parcel-auth
    environment:
      - CONSUL_SERVER_HOST=consul
      - CONSUL_SERVER_PORT=8500
      - DB_HOST=guava-postgresql
      - DB_PORT=5432
      - DB_NAME=guava
      - DB_USER=guava
      - DB_PASSWORD=guava
    depends_on:
      - consul
      - guava-postgresql
  guava-parcel-delivery:
    build: ../guava-parcel-delivery
    environment:
      - CONSUL_SERVER_HOST=consul
      - CONSUL_SERVER_PORT=8500
      - DB_HOST=guava-postgresql
      - DB_PORT=5432
      - DB_NAME=guava
      - DB_USER=guava
      - DB_PASSWORD=guava
    depends_on:
      - consul
      - guava-postgresql
  guava-parcel-admin:
    build: ../guava-parcel-admin
    environment:
      - CONSUL_SERVER_HOST=consul
      - CONSUL_SERVER_PORT=8500
    depends_on:
      - consul
  guava-parcel-courier:
    build: ../guava-parcel-courier
    environment:
      - CONSUL_SERVER_HOST=consul
      - CONSUL_SERVER_PORT=8500
      - KAFKA_BOOTSTRAP_SERVERS=kafka
    depends_on:
      - consul