spring:
  main:
    banner-mode: off
  application:
    name: guava-parcel-delivery
  cloud:
    consul:
      host: "localhost"
      port: 8500
      discovery:
        prefer-ip-address: true
        health-check-interval: 15s
        health-check-timeout: 60s
        health-check-critical-timeout: 3m
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/guava"
    username: "guava"
    password: "guava"
    properties:
      schema: "guava_delivery"
  liquibase:
    url: "jdbc:postgresql://localhost:5432/guava"
    user: "guava"
    password: "guava"
    change-log: "classpath:db/changelog/master.yaml"
    database-change-log-table: "guava_delivery_change_log"
    database-change-log-lock-table: "guava_delivery_change_log_lock"
    liquibase-schema: public
    default-schema: "guava_delivery"
server:
  port: 0
