spring:
  main:
    banner-mode: off
  application:
    name: guava-parcel-delivery
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/guava"
    username: "guava"
    password: "guava"
    properties:
      schema: "guava_delivery"
  liquibase:
    url: "jdbc:postgresql://localhost:5432/guava"
    user: "guava"
    password: "guava"
    change-log: "classpath:db/changelog/master.yaml"
    database-change-log-table: "guava_delivery_change_log"
    database-change-log-lock-table: "guava_delivery_change_log_lock"
    liquibase-schema: public
    default-schema: "guava_delivery"
server:
  port: 0
