server:
  port: 0
spring:
  main:
    banner-mode: off
  application:
    name: guava-parcel-auth
  cloud:
    consul:
      host: ${CONSUL_SERVER_HOST:localhost}
      port: ${CONSUL_SERVER_PORT:8500}
      discovery:
        prefer-ip-address: true
        health-check-interval: 15s
        health-check-timeout: 60s
        health-check-critical-timeout: 3m
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    properties:
      schema: "guava_auth"
  liquibase:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    change-log: "classpath:db/changelog/master.yaml"
    database-change-log-table: "guava_auth_change_log"
    database-change-log-lock-table: "guava_auth_change_log_lock"
    liquibase-schema: public
    default-schema: "guava_auth"

springdoc:
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
  api-docs:
    path: /swagger-doc/v3/api-docs