server:
  port: 8080
spring:
  application:
    name: guava-parcel-gateway
  cloud:
    consul:
      host: ${CONSUL_SERVER_HOST:localhost}
      port: ${CONSUL_SERVER_PORT:8500}
      discovery:
        prefer-ip-address: true
        health-check-interval: 15s
        health-check-timeout: 60s
        health-check-critical-timeout: 3m
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    gateway:
      routes:
        - id: guava-parcel-admin
          uri: lb://guava-parcel-admin
          predicates:
            - Path=/guava-parcel-admin/**
          filters:
            - RewritePath=/guava-parcel-admin/(?<segment>.*), /$\{segment}
        - id: guava-parcel-courier
          uri: lb://guava-parcel-courier
          predicates:
            - Path=/guava-parcel-courier/**
          filters:
            - RewritePath=/guava-parcel-courier/(?<segment>.*), /$\{segment}
        - id: guava-parcel-user
          uri: lb://guava-parcel-user
          predicates:
            - Path=/guava-parcel-user/**
          filters:
            - RewritePath=/guava-parcel-user/(?<segment>.*), /$\{segment}
management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true